### ISSUE TITLE
C-goals

### ISSUE THREAD

**Issue by sheeralm** [reedKlein/Data-Vis-Project2#2]
The first set of goals are to show the 311 calls dataset on a map, with an additional timeline view, with some interactivity. 

MAP: 
1. Show the locations of 311 calls (columns labeled latitude and longitude) on a zoomable interactive map, using Leaflet and d3.  This will allow the user to see the spatial distribution of calls, zoom in and see details of the site, and relate this spatial positioning to other data fields.  
2. Default zoom and positioning: When we open your application, I suggest setting an initial zoom level and center position for the map, so the user immediately sees the data without needing to pan and zoom.   
3. Encoding: Show each call as a colored point on the map (color scheme options below), positioned by latitude and longitude.  I have tested displaying these points, and have not had performance lags, so this should be achievable. Let me know ASAP of performance issues. 
4. Details on demand:  When hovering over a point, provide details-on-demand about the call.  This should include the date of the call, the updated date, the public agency handling the call, the type of call and descriptive information.  Note- some entries may not have GPS coordinates.  Don't eliminate these items altogether, because they are part of the dataset and should be featured in the other charts.  You could indicate somewhere within the visualization how many calls are not mapped. 
5. Provide a set of 'color by' options for the points on the map, which the user can activate through user interface elements:
6. color by call type (service code or service name)
7. Note- you may need to group these categories together to avoid using too many categorical colors
8. color by time between the requested date and the updated date 
9. color to indicate how far into the year the call was placed
10. color by public agency responding to the calls 
11. design explanation for documentation:  describe the colors you selected for these options and why you selected them, referencing whether the data is nominal, ordinal, quantitative, etc. and whether the color scheme is monochromatic, diverging, or categorical.  
12. Add a button that allows the user to toggle between different map background- such as from aerial images to one that shows roads/boundaries/etc.   
13. Find backgrounds here:  https://leaflet-extras.github.io/leaflet-providers/preview/

TIMELINE:
1. The page should include a timeline of when calls were placed over the complete timeframe.  This view of the data should allow someone to see when in the year most calls were placed. 
2. The timeline view should be clearly labeled, with axes that make it easy to interpret the data
3. The timeline view should be long enough to allow someone to see trends over time and variations in number of calls. 
4. You can binned into appropriate sized timeframes.  You can bin into an appropriate size interval- I would suggest daily or weekly, to give enough granularity in the timeline. 
5. Design choices:  Choose how you want to represent the data in this timeline.  Do you want to show a line chart, a bar chart, a heat-map, a plot of individual samples by time?  Draw a sketch of your intended visualization and explain your design choices. 
6. Choose how to use color for your timeline.  Are you using a neutral, desaturated color or a color scale?  Why did you make this choice?  
7. Details on demand: When hovering over the timeline, provide a tooltip to give the user more information about the timeframe they are hovering over.  For instance, if plotting the data by week, show the selected week and the number of calls.

**Comment by sheeralm** [comment]
progres-

i did this

**Comment by reedKlein** [comment]
Currently working on finishing the functionality for all the C goals. We'll have to come back and make it look nice later. 
Done: All of timeline, All of map except for color coding for the "color by" goal.

Working on: Color by goal

**Comment by sheeralm** [comment]
Currently working on UI

**Comment by reedKlein** [comment]
Complete. We'll go over these before turn-in
